services:
  redis:
    image: redis:7-alpine
    container_name: smart_tasks_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:7
    container_name: smart_tasks_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smart-tasks
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  server:
    build: ./server
    container_name: smart_tasks_server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/smart-tasks
      JWT_SECRET: change_this_super_secret_in_prod
      VAPID_PUBLIC_KEY: BKs-qGrloipRm1Fm_N-8LK4kiopBlhkd457f2aB1sL-i27JSdaT3oCQ_Ixl336wgwdFOPPP_WB5iWw5a8WdLDYk
      VAPID_PRIVATE_KEY: C7HQjh-OiSlp01RF28gfkk1XsIIVtg-6-1K_idV-7RY
      VAPID_SUBJECT: mailto:admin@smarttasks.local
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  client:
    build: ./client
    container_name: smart_tasks_client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data:
  redis_data:
